### ISSUE TITLE
Allow to specify output folder for downloading images

### ISSUE THREAD

**Issue by xssChauhan** [gurugaurav/bing_image_downloader#1]
Currently the script downloads the images to a `dataset` folder in the repo.
This is not always desirable. 

Modify the signature of `downloader.download` to specify the `output_dir` for image downloads.

**Comment by Yuannan97** [comment]
are there any other arguments that we can set? I mean like old google-image-download

**Comment by gurugaurav** [comment]
Hi, Added `output_dir` parameter for custom output dir. Please refer the [Readme](https://github.com/gurugaurav/bing_image_downloader/blob/master/README.md#usage-)
