### ISSUE TITLE
Circular import

### ISSUE THREAD

**Issue by Agstarte** [gurugaurav/bing_image_downloader#10]
I can't run code because of AttributeError.
![image](https://user-images.githubusercontent.com/51338328/101623929-7830f580-3a19-11eb-91cb-302ce632aa26.png)

**Comment by Agstarte** [comment]
I did solve this problem by running download.py itself but i don't think it should work this way.

**Comment by MtNoot** [comment]
this is because you saved your program as bing.py, when downloader,py tries to import the bing module it imports your module instead causing a circular import. If you change the name of your program to something else it should work normally
