### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by jesgarm** [gurugaurav/bing_image_downloader#14]
Hello,
I have been using the python package for months without problems, but for a few weeks the downloaded images have no relation to the search tag and the downloads are repeated cyclically.

I mean if i search for example "box" and try to download 50 images. There are many images that are not related to boxes, and every 8 images they repeat.

**Comment by jesgarm** [comment]
It just works again! No change, the downloader now downloads differente images and not repeating

**Comment by c-shekhar** [comment]
> Hello,
> I have been using the python package for months without problems, but for a few weeks the downloaded images have no relation to the search tag and the downloads are repeated cyclically.
> 
> I mean if i search for example "box" and try to download 50 images. There are many images that are not related to boxes, and every 8 images they repeat.

@gurugaurav this is happening again. Thought maybe lot of calls from a particular network resulting in this so, tried from different network but, that doesn't seem to be the issue. Can you please check?

**Comment by chinmayjog13** [comment]
I'm facing the same issue. Uninstalled and installed again, but still get the same 12 images repeated. @jesgarm any advice?

**Comment by c-shekhar** [comment]
@chinmayjog13, please modify [header](https://github.com/gurugaurav/bing_image_downloader/blob/master/bing_image_downloader/bing.py#L29) and it should work.
