### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by ggc161169** [gurugaurav/bing_image_downloader#4]
Hi, if I use bing.py and downloader.py outside the package they work perfectly. But if I import as it is in the instructions it generates `ImportError: cannot import name downloader from partially initialized module bing_image_downloader`.

**Comment by gurugaurav** [comment]
Hi, Can you please post how to reproduce the error.

**Comment by ggc161169** [comment]
This was done today on a PC where I did not have the module installed previously, then I will test again on the machine where I had tested it before.

**Comment by gurugaurav** [comment]
It seems pip and python binary are from different distribution.  Can you please post the output of ` python -m pip freeze`
