### ISSUE TITLE
Path problems

### ISSUE THREAD

**Issue by Johanfer12** [gurugaurav/bing_image_downloader#5]
Hello!, when I put a destination folder the script tries to generate a folder with the name of the path I indicated, for example if I put in path "C:\" it doesn't locate the images in that path but tries to create a folder called C:\ which generates an error, is there a way to solve this?

Is there also a way to rename the downloaded file and not generate a folder with the name of each search but keep them all in the same folder?

Thank you very much!

**Comment by gurugaurav** [comment]
For now path is always relative. Will change it to absolute in next release.
